services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "SenhaSegura123!" # Defina uma senha segura aqui
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: "SenhaDoUsuario123!" 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  app:
    image: node:18
    container_name: prisma_app
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge